TheaterReservering/Models/Klant.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace TheaterReservering.Models
{
    public class Klant
    {
        public int Id { get; set; }
        [MinLength(2)]
        public string Naam { get; set; }
        [Required]
        public string Adres { get; set; }
        [Required]
        public string Woonplaats { get; set; }
        [EmailAddress]
        public string Email { get; set; }
        [NotMapped]
        public int Prijs { get; set; }
        public ICollection<Reservering> Reserveringen { get; set; }
    }
}

TheaterReservering/Controllers/KlantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TheaterReservering.Data;
using TheaterReservering.Models;

namespace TheaterReservering.Controllers
{
    public class KlantController : Controller
    {
        private readonly TheaterReserveringContext _context;

        public KlantController(TheaterReserveringContext context)
        {
            _context = context;
        }

        // GET: Klant
        public async Task<IActionResult> Index()
        {
            ICollection<Klant> klanten = _context.Klant.OrderBy(k => k.Naam).Include(k => k.Reserveringen).ToList();
            
            foreach(Klant klant in klanten)
            {
                klant.Prijs = await APICaller.CallBerekenPrijsAsync(klant.Id);
            }
            
            return View(klanten);
        }

        // GET: Klant/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var klant = await _context.Klant
                .FirstOrDefaultAsync(m => m.Id == id);
            if (klant == null)
            {
                return NotFound();
            }

            return View(klant);
        }

        // GET: Klant/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Klant/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Naam,Adres,Woonplaats,Email")] Klant klant)
        {
            if (ModelState.IsValid)
            {
                _context.Add(klant);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(klant);
        }

        // GET: Klant/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var klant = await _context.Klant.FindAsync(id);
            if (klant == null)
            {
                return NotFound();
            }
            return View(klant);
        }

        // POST: Klant/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Naam,Adres,Woonplaats,Email")] Klant klant)
        {
            if (id != klant.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(klant);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!KlantExists(klant.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(klant);
        }

        // GET: Klant/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var klant = await _context.Klant
                .FirstOrDefaultAsync(m => m.Id == id);
            if (klant == null)
            {
                return NotFound();
            }

            return View(klant);
        }

        // POST: Klant/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var klant = await _context.Klant.FindAsync(id);
            _context.Klant.Remove(klant);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool KlantExists(int id)
        {
            return _context.Klant.Any(e => e.Id == id);
        }
    }
}

TheaterReservering/Controllers/ReserveringController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.EntityFrameworkCore;
using TheaterReservering.Data;
using TheaterReservering.Models;

namespace TheaterReservering.Controllers
{
    public class ReserveringController : Controller
    {
        private readonly TheaterReserveringContext _context;

        public ReserveringController(TheaterReserveringContext context)
        {
            _context = context;
        }

        // GET: Reservering
        public async Task<IActionResult> Index()
        {
            var theaterReserveringContext = _context.Reservering.Include(r => r.Klant);
            return View(await theaterReserveringContext.ToListAsync());
        }

        public async Task<IActionResult> EditWithKlantId(int? id)
        {
            if (id == null)
                return NotFound();

            Klant klant = _context.Klant.FirstOrDefault(k => k.Id == id);

            if (klant == null)
                return NotFound();

            var reserveringen = _context.Reservering.Include(r => r.Klant).OrderBy(r => r.Naam);

            ViewData["Klant"] = $"{klant.Naam}, {klant.Email}, {klant.Woonplaats}";
            ViewData["KlantId"] = klant.Id;

            return View(await reserveringen.ToListAsync());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditWithKlantId(int id, int[] reserveringsIds)
        {
            if (ModelState.IsValid)
            {
                // Verwijder eerst alle reserveringen van Klant
                ICollection<Reservering> reserveringen = _context.Reservering.Where(r => r.KlantId == id).ToList();
                foreach(Reservering r in reserveringen)
                {
                    r.KlantId = null;
                    r.Bezet = false;
                    _context.Update(r);
                    _context.SaveChanges();
                }
                // Voeg alle reserveringen toe die zijn meegegeven
                foreach(int rid in reserveringsIds)
                {
                    Reservering reservering = _context.Reservering.Find(rid);
                    if(reservering != null)
                    {
                        reservering.KlantId = id;
                        reservering.Bezet = true;
                        _context.Update(reservering);
                        _context.SaveChanges();
                    }
                }
                return RedirectToAction(nameof(Index), "Klant");
            }
            return RedirectToAction(nameof(Index), "Klant");
        }

        // GET: Reservering/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reservering = await _context.Reservering
                .Include(r => r.Klant)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (reservering == null)
            {
                return NotFound();
            }

            return View(reservering);
        }

        // GET: Reservering/Create
        public IActionResult Create()
        {
            ViewData["KlantId"] = new SelectList(_context.Klant, "Id", "Adres");
            return View();
        }

        // POST: Reservering/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Naam,Bezet,KlantId")] Reservering reservering)
        {
            if (ModelState.IsValid)
            {
                _context.Add(reservering);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["KlantId"] = new SelectList(_context.Klant, "Id", "Adres", reservering.KlantId);
            return View(reservering);
        }

        // GET: Reservering/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reservering = await _context.Reservering.FindAsync(id);
            if (reservering == null)
            {
                return NotFound();
            }
            ViewData["KlantId"] = new SelectList(_context.Klant, "Id", "Adres", reservering.KlantId);
            return View(reservering);
        }

        // POST: Reservering/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Naam,Bezet,KlantId")] Reservering reservering)
        {
            if (id != reservering.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(reservering);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReserveringExists(reservering.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["KlantId"] = new SelectList(_context.Klant, "Id", "Adres", reservering.KlantId);
            return View(reservering);
        }

        // GET: Reservering/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reservering = await _context.Reservering
                .Include(r => r.Klant)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (reservering == null)
            {
                return NotFound();
            }

            return View(reservering);
        }

        // POST: Reservering/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var reservering = await _context.Reservering.FindAsync(id);
            _context.Reservering.Remove(reservering);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ReserveringExists(int id)
        {
            return _context.Reservering.Any(e => e.Id == id);
        }
    }
}

TheaterReservering/Views/Klant/Create.cshtml
@model TheaterReservering.Models.Klant

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Klant</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Naam" class="control-label"></label>
                <input asp-for="Naam" class="form-control" />
                <span asp-validation-for="Naam" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adres" class="control-label"></label>
                <input asp-for="Adres" class="form-control" />
                <span asp-validation-for="Adres" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Woonplaats" class="control-label"></label>
                <input asp-for="Woonplaats" class="form-control" />
                <span asp-validation-for="Woonplaats" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TheaterReservering/Views/Klant/Delete.cshtml
@model TheaterReservering.Models.Klant

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Klant</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Naam)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Naam)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Adres)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Adres)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Woonplaats)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Woonplaats)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

TheaterReservering/Views/Klant/Details.cshtml
@model TheaterReservering.Models.Klant

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Klant</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Naam)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Naam)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Adres)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Adres)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Woonplaats)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Woonplaats)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

TheaterReservering/Views/Klant/Edit.cshtml
@model TheaterReservering.Models.Klant

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Klant</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Naam" class="control-label"></label>
                <input asp-for="Naam" class="form-control" />
                <span asp-validation-for="Naam" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adres" class="control-label"></label>
                <input asp-for="Adres" class="form-control" />
                <span asp-validation-for="Adres" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Woonplaats" class="control-label"></label>
                <input asp-for="Woonplaats" class="form-control" />
                <span asp-validation-for="Woonplaats" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TheaterReservering/Views/Klant/Index.cshtml
@model IEnumerable<TheaterReservering.Models.Klant>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Naam)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Woonplaats)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>Reserveringen</th>
            <th>
                @Html.DisplayNameFor(model => model.Prijs)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Naam)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Woonplaats)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @{
                    var cnt = 1;
                    foreach (Reservering res in item.Reserveringen)
                    {
                        if (cnt++ % 5 == 0)
                        {
                            @:<br />
                        }
                        @res.Naam @:&nbsp;
                    }
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Prijs)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                <a asp-controller="Reservering" asp-action="EditWithKlantId" asp-route-id="@item.Id" class="btn btn-primary">Reserveren</a>
            </td>
        </tr>
}
    </tbody>
    <tfoot>
        <tr>
            <td><b>Aantal klanten is:</b></td>
            <td><b>@Model.Count()</b></td>
        </tr>
    </tfoot>
</table>